/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWealthRouteImport } from './routes/app.wealth'
import { Route as AppTradingRouteImport } from './routes/app.trading'
import { Route as AppTrackRouteImport } from './routes/app.track'
import { Route as AppSsiRouteImport } from './routes/app.ssi'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMemoryRouteImport } from './routes/app.memory'
import { Route as AppLivingRouteImport } from './routes/app.living'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppContinuityRouteImport } from './routes/app.continuity'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppActivityRouteImport } from './routes/app.activity'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWealthRoute = AppWealthRouteImport.update({
  id: '/wealth',
  path: '/wealth',
  getParentRoute: () => AppRoute,
} as any)
const AppTradingRoute = AppTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackRoute = AppTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AppRoute,
} as any)
const AppSsiRoute = AppSsiRouteImport.update({
  id: '/ssi',
  path: '/ssi',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppLivingRoute = AppLivingRouteImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppContinuityRoute = AppContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/status': typeof StatusRoute
  '/app/activity': typeof AppActivityRoute
  '/app/ai': typeof AppAiRoute
  '/app/continuity': typeof AppContinuityRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/health': typeof AppHealthRoute
  '/app/living': typeof AppLivingRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/ssi': typeof AppSsiRoute
  '/app/track': typeof AppTrackRoute
  '/app/trading': typeof AppTradingRoute
  '/app/wealth': typeof AppWealthRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/app/activity': typeof AppActivityRoute
  '/app/ai': typeof AppAiRoute
  '/app/continuity': typeof AppContinuityRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/health': typeof AppHealthRoute
  '/app/living': typeof AppLivingRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/ssi': typeof AppSsiRoute
  '/app/track': typeof AppTrackRoute
  '/app/trading': typeof AppTradingRoute
  '/app/wealth': typeof AppWealthRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/status': typeof StatusRoute
  '/app/activity': typeof AppActivityRoute
  '/app/ai': typeof AppAiRoute
  '/app/continuity': typeof AppContinuityRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/guide': typeof AppGuideRoute
  '/app/health': typeof AppHealthRoute
  '/app/living': typeof AppLivingRoute
  '/app/memory': typeof AppMemoryRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/skills': typeof AppSkillsRoute
  '/app/ssi': typeof AppSsiRoute
  '/app/track': typeof AppTrackRoute
  '/app/trading': typeof AppTradingRoute
  '/app/wealth': typeof AppWealthRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/status'
    | '/app/activity'
    | '/app/ai'
    | '/app/continuity'
    | '/app/contracts'
    | '/app/guide'
    | '/app/health'
    | '/app/living'
    | '/app/memory'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/research'
    | '/app/settings'
    | '/app/skills'
    | '/app/ssi'
    | '/app/track'
    | '/app/trading'
    | '/app/wealth'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/app/activity'
    | '/app/ai'
    | '/app/continuity'
    | '/app/contracts'
    | '/app/guide'
    | '/app/health'
    | '/app/living'
    | '/app/memory'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/research'
    | '/app/settings'
    | '/app/skills'
    | '/app/ssi'
    | '/app/track'
    | '/app/trading'
    | '/app/wealth'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/status'
    | '/app/activity'
    | '/app/ai'
    | '/app/continuity'
    | '/app/contracts'
    | '/app/guide'
    | '/app/health'
    | '/app/living'
    | '/app/memory'
    | '/app/onboarding'
    | '/app/portfolio'
    | '/app/research'
    | '/app/settings'
    | '/app/skills'
    | '/app/ssi'
    | '/app/track'
    | '/app/trading'
    | '/app/wealth'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wealth': {
      id: '/app/wealth'
      path: '/wealth'
      fullPath: '/app/wealth'
      preLoaderRoute: typeof AppWealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trading': {
      id: '/app/trading'
      path: '/trading'
      fullPath: '/app/trading'
      preLoaderRoute: typeof AppTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/track': {
      id: '/app/track'
      path: '/track'
      fullPath: '/app/track'
      preLoaderRoute: typeof AppTrackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ssi': {
      id: '/app/ssi'
      path: '/ssi'
      fullPath: '/app/ssi'
      preLoaderRoute: typeof AppSsiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memory': {
      id: '/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/living': {
      id: '/app/living'
      path: '/living'
      fullPath: '/app/living'
      preLoaderRoute: typeof AppLivingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/continuity': {
      id: '/app/continuity'
      path: '/continuity'
      fullPath: '/app/continuity'
      preLoaderRoute: typeof AppContinuityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAiRoute: typeof AppAiRoute
  AppContinuityRoute: typeof AppContinuityRoute
  AppContractsRoute: typeof AppContractsRoute
  AppGuideRoute: typeof AppGuideRoute
  AppHealthRoute: typeof AppHealthRoute
  AppLivingRoute: typeof AppLivingRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppSsiRoute: typeof AppSsiRoute
  AppTrackRoute: typeof AppTrackRoute
  AppTradingRoute: typeof AppTradingRoute
  AppWealthRoute: typeof AppWealthRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAiRoute: AppAiRoute,
  AppContinuityRoute: AppContinuityRoute,
  AppContractsRoute: AppContractsRoute,
  AppGuideRoute: AppGuideRoute,
  AppHealthRoute: AppHealthRoute,
  AppLivingRoute: AppLivingRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppResearchRoute: AppResearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppSsiRoute: AppSsiRoute,
  AppTrackRoute: AppTrackRoute,
  AppTradingRoute: AppTradingRoute,
  AppWealthRoute: AppWealthRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
